---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 73493.
--- DateTime: 2023-10-14 13:10
---
if (redis.call('GET', KEYS[1]) == ARGV[1]) then
    -- 一致，则删除锁
    return redis.call('DEL', KEYS[1])
end
-- 不一致，则直接返回
return 0