server:
  port: 6060

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: rocketmq-4x-service_common-message-execute_pg
    send-message-timeout: 2000
    retry-times-when-send-failed: 1
    retry-times-when-send-async-failed: 1
